### ISSUE TITLE
rspec-puppet-4.0.2.gem doesn't contain LICENSE file, is this intentional?

### ISSUE THREAD

**Issue by micwoj92** [puppetlabs/rspec-puppet#107]
## Describe the Bug
The gem that one can get from rubygems does not have the `LICENSE` file in it.
I did not check if previous versions contain license.

## Expected Behavior
`LICENSE` file within the gem

## Steps to Reproduce
1. obtain gem
2. unpack
3. no LICENSE
![image](https://github.com/puppetlabs/rspec-puppet/assets/45581170/97c846b5-0074-48e1-b46b-5c4b493e268b)

## Environment
 - Version: 4.0.2
 - Platform: N/A

## Additional Context
Usually gems have license file within the gem.

**Comment by jordanbreen28** [comment]
@micwoj92 definitely not intentional... Thank you for raising this!
I've got a PR raised to fix this.
