### ISSUE TITLE
raise ruby version requirement to 2.7.4

### ISSUE THREAD

**Issue by UiP9AV6Y** [puppetlabs/rspec-puppet#87]
the gemspec lists the minimum requirement for the gem release 4.0.0 as [2.7.0](https://github.com/puppetlabs/rspec-puppet/blob/a9620d53dc3a68a6b9e862b7ac779e1ede834fdf/rspec-puppet.gemspec#L27)

the dynamic matcher [implementation](https://github.com/puppetlabs/rspec-puppet/blob/a9620d53dc3a68a6b9e862b7ac779e1ede834fdf/lib/rspec-puppet/matchers/dynamic_matchers.rb#L29) makes use of a feature introduced with 2.7.0 (according to the [changelog](https://github.com/ruby/ruby/blob/647ee6f091eafcce70ffb75ddf7e121e192ab217/NEWS?plain=1#L229))

however: loading the gem with ruby 2.7.0 leads to a syntax
error:

> $ ruby --version
> ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
> $ gem install --silent --version "~>7" puppet
> $ gem install --silent --version "~>4" rspec-puppet
> $ ruby -e "require 'rspec-puppet'"
> ...
> /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require': /usr/local/bundle/gems/rspec-puppet-4.0.0/lib/rspec-puppet/matchers/dynamic_matchers.rb:29: syntax error, unexpected (... (SyntaxError)
... def method_missing(method, ...)
...                            ^~~
/usr/local/bundle/gems/rspec-puppet-4.0.0/lib/rspec-puppet/matchers/dynamic_matchers.rb:30: syntax error, unexpected ')'
...:CreateGeneric.new(method, ...) if method == :be_valid_type
...                              ^
/usr/local/bundle/gems/rspec-puppet-4.0.0/lib/rspec-puppet/matchers/dynamic_matchers.rb:35: syntax error, unexpected `end', expecting end-of-input

whereas loading the gem with ruby 2.7.4 succeeds:

> $ ruby --version
> ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
> $ gem install --silent --version "~>7" puppet
> $ gem install --silent --version "~>4" rspec-puppet
> $ ruby -e "require 'rspec-puppet'"
> $ echo $?
> 0

i came across this issues, as ruby [2.7.0](https://packages.ubuntu.com/focal/ruby2.7) is the version shipped with Ubuntu 20.04 (EOL in [2025](https://wiki.ubuntu.com/Releases))

**Comment by ekohl** [comment]
Looks like this was introduced in a16dc28e02c6fcdb786b719dd12ec5e947bffc14. I've opened https://github.com/puppetlabs/rspec-puppet/pull/88 to see if it can be reproduced by testing on 2.7.0 instead of 2.7.latest.

**Comment by jordanbreen28** [comment]
Fixed and released as part of v4.0.2.
Thanks both
